# Generated by Django 3.1.2 on 2020-12-12 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.TextField()),
                ('movieName', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='reviews.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('role', models.BooleanField()),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('ranking', models.IntegerField(max_length=11)),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='reviews.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='reviews.user')),
            ],
        ),
    ]
